log:
  level: debug
root: assets/simple_app
dsn:
  - dbi:SQLite:dbname=assets/simple_app/data.sqlite
  -
  -
session:
  store:
    class: DBM
    args:
      file: /tmp/simple_app_session.dbm
      dbm_class: DB_File
  state:
    class: Cookie
    args:
      name: simple_app_session_id
include_path:
  - assets/admin_console/templates
